# -*- coding: utf-8 -*-
"""DF_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1972wBQlMVaN1fWSRSA_aJbwAP_zRUwdx
"""

import pandas as pd

# Load the data directly from the URL into a Pandas DataFrame
url = "https://data.cityofchicago.org/resource/ijzp-q8t2.csv"
df = pd.read_csv(url)

# Display the first few rows of the DataFrame (optional)
display(df.head())

